### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by sleeyax** [tymmesyde/stremio-desktop#1]
I'm getting the following error on startup:
```
App threw an error during load
TypeError: electron.protocol.registerSchemesAsPrivileged is not a function
    at module.exports.options (D:\Documents\Programming\javascript\electron\stremio-desktop\node_modules\electron-serve\index.js:53:20)
    at Object.<anonymous> (D:\Documents\Programming\javascript\electron\stremio-desktop\src\main\index.js:22:17)
    at Object.<anonymous> (D:\Documents\Programming\javascript\electron\stremio-desktop\src\main\index.js:94:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at loadApplicationPackage (C:\Users\Quinten\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:119:12)      
    at Object.<anonymous> (C:\Users\Quinten\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:164:5)
    at Object.<anonymous> (C:\Users\Quinten\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:204:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```
This causes the electron windows to not show at all.

![image](https://user-images.githubusercontent.com/30344294/107119219-7bfcbf00-6886-11eb-97dc-9d0b9dbe0350.png)

Steps to reproduce:

1. run `npm install`
2. run `npm start`

**Comment by sleeyax** [comment]
I had electron 4 globally installed on my system and since `electron` wasn't installed as a non-dev dependency it took precedence over the local v11.x.x one.
